name: Pint
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'dependabot/npm_and_yarn/*'
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: "laravel-pint"
        uses: aglipanci/laravel-pint-action@0.1.0
        with:
          preset: laravel

#      - name: Prettify code
#        uses: creyD/prettier_action@v4.3
#        with:
#          # This part is also where you can pass other options, for example:
#          prettier_options: --config ./frontend/.prettierrc.json --write ./frontend/**/*.{js,ts,md,vue,json,html,css}
#          only_changed: True
#          commit_message: "[skip netlify]"
